config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:sessions], controllers: { registrations: 'registrations' }
  as :user do
  #  get     'signup',       to: 'devise/registrations#new', as: 'new_user_registration_path'
  #  post    'signup',       to: 'devise/registrations#create', as: ''
   get     'admin/login',   to: 'devise/sessions#new',      as: 'new_user_session'
   post    'admin/login',   to: 'devise/sessions#create',   as: 'user_session'
   delete  'admin/logout',  to: 'devise/sessions#destroy',  as: 'destroy_user_session'
  end

  namespace 'admin' do
    resources :books, only: [ :new, :create, :edit, :update, :index, :destroy ]
    resources :watched_videos, only: [ :new, :create, :edit, :update, :index, :destroy ]
    resources :projects, only: [ :index, :new, :create, :edit, :update, :destroy ]
    resources :skills, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      put :sort, on: :collection
    end
  end

  resources :books, only: [ :index ]
  resources :watched_videos, only: [ :index ]
  resources :projects, only: [ :index ]

  get  '/contact_me',  to: 'email_messages#new',    as: 'new_email_message'
  post '/contact_me',  to: 'email_messages#create', as: 'email_message'

  match '/404',       to: 'errors#not_found',       via: :all
  match '/500',       to: 'errors#server_error',    via: :all
  match '*path',      to: 'errors#not_found',     via: :all

  root to: 'pages#home'
end

app/models/skill.rb
class Skill < ApplicationRecord
  # validation rules
  validates_presence_of   :name

  # methods
  def name_in_dash_case
    name.gsub(/\s/, '-').downcase
  end

  def self.by_orderno
    order("orderno ASC")
  end
end

app/controllers/admin/skills_controller.rb
module Admin
  class SkillsController < ApplicationController
    before_action :authenticate_user!, only: [ :index, :sort, :new, :edit, :destroy ]
    before_action :set_skill, only: [ :edit, :update, :destroy ]
    layout "admin"

    # calls index view and displays a list of skills
    def index
      @skills = Skill.by_orderno
    end

    # accepts list of skills and applies changes to orderno of
    # skill in the request that has been modified
    def sort
      params[:skill].each do |key, value|
        Skill.find(value[:id]).update!(orderno: value[:orderno])
      end
    end

    # calls view to be rendered to add a new skill
    def new
      @skill = Skill.new
    end

    # ingests valid parameters and adds a new skill
    def create
      @skill = Skill.new(skill_params)

      respond_to do |format|
        if @skill.save
          format.html { redirect_to admin_skills_path, 
                        notice: 'Skill was successfully added.' }
        else
          format.html { render :new }
        end
      end
    end

    # calls view to be rendered for editing a skill
    def edit
    end

    # ingests valid parameters and applies changes to a specific skill
    def update
      respond_to do |format|
        if @skill.update(skill_params)
          format.html { redirect_to admin_skills_path, 
                        notice: 'Skill was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end

    # removes a skill from list
    def destroy
      @skill.destroy

      respond_to do |format|
        format.html { redirect_to admin_skills_path, 
                      notice: 'Skill was successfully deleted.' }
      end
    end

    private
    # identifies a specific skill from id parameter in request
    def set_skill
      @skill = Skill.find(params[:id])
    end
    # specifies valid parameters that may be ingested by
    # the skills resource
    def skill_params
      params.require(:skill).permit(:name)
    end
  end
end

app/views/admin/skills/edit.html.erb
<div class="py-3">
  <h1 class="mb-3">Edit Skill</h2>

  <%= form_for(@skill, url: admin_skill_path(@skill)) do |f| %>

    <%= display_form_errors_for @skill %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit "Apply Changes", class: 'btn btn-primary mr-2' %>
      <%= link_to "Back", admin_skills_path, class: 'btn btn-light'%>
    </div>

  <% end %>
</div>

app/views/admin/skills/index.html.erb
<div class="w-100 my-3 py-3">

  <h3 class="my-3">List of Skills</h3>

  <%= link_to icon("fas", "plus-circle", "Add New Skill"), new_admin_skill_path, class: 'btn btn-dark mb-5' %>

  <% if @skills.count > 0 %>

    <div class="row p-1 border-bottom">
      <div class="col h6">Name</div>
    </div>

    <div class="row sortable p-1">
    
    <% @skills.each do |skill| %>

        <div class="col-md-12">
          <div class="skill-item row p-1 border-bottom" data-skill-id="<%= skill.id %>">
            <div class="col-9">
              <%= icon("fas", "sort", skill.name) %>
            </div>
            <div class="col-3 text-right">
              <%= link_to icon("fas", "pen"), edit_admin_skill_path(skill), class: 'btn btn-outline-secondary btn-sm mr-1' %>
              <%= link_to icon("fas", "trash-alt"), admin_skill_path(skill), method: :delete, 
                                                            data: { confirm: 'Are you sure you want to delete this skill?' }, 
                                                            class: 'btn btn-outline-danger btn-sm' %>
            </div>
          </div>
        </div>

    <% end %>

    </div>

  <% else %>

    <div class="row">
      <div class="col em">
        <p><em>There are no skills added yet.</em></p>
      </div>
    </div>

  <% end %>
  
</div>

app/views/admin/skills/new.html.erb
<div class="py-3">
  <h1 class="mb-3">Add a Skill</h1>

  <%= form_for(@skill, url: admin_skills_path) do |f| %>

    <%= display_form_errors_for @skill %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', autofocus: true, placeholder: 'Add ...' %>
    </div>

    <div class="form-group">
      <%= f.submit "Add Skill", class: 'btn btn-primary mr-2' %>
      <%= link_to "Back", admin_skills_path, class: 'btn btn-light'%>
    </div>

  <% end %>
</div>