config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:sessions], controllers: { registrations: 'registrations' }
  as :user do
  #  get     'signup',       to: 'devise/registrations#new', as: 'new_user_registration_path'
  #  post    'signup',       to: 'devise/registrations#create', as: ''
   get     'admin/login',   to: 'devise/sessions#new',      as: 'new_user_session'
   post    'admin/login',   to: 'devise/sessions#create',   as: 'user_session'
   delete  'admin/logout',  to: 'devise/sessions#destroy',  as: 'destroy_user_session'
  end

  namespace 'admin' do
    resources :books, only: [ :new, :create, :edit, :update, :index, :destroy ]
    resources :watched_videos, only: [ :new, :create, :edit, :update, :index, :destroy ]
    resources :projects, only: [ :index, :new, :create, :edit, :update, :destroy ]
    resources :skills, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      put :sort, on: :collection
    end
  end

  resources :books, only: [ :index ]
  resources :watched_videos, only: [ :index ]
  resources :projects, only: [ :index ]

  get  '/contact_me',  to: 'email_messages#new',    as: 'new_email_message'
  post '/contact_me',  to: 'email_messages#create', as: 'email_message'

  match '/404',       to: 'errors#not_found',       via: :all
  match '/500',       to: 'errors#server_error',    via: :all
  match '*path',      to: 'errors#not_found',     via: :all

  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  include Coverable

  #validation rules
  validates_presence_of   :title, :date_read
  validates               :link, presence: true,
                                 url: true
  validates_presence_of   :image, message: 'Hey, quit being lazy and add the cover of this book!'

  # scopes
  def self.last_read
    order(date_read: :desc)
  end
end

app/models/email_message.rb
class EmailMessage
  include ActiveModel::Model

  attr_accessor :name, :company, :email, :phone, :preferred_method, :reason, :brief_msg

  REASONS = {
    :general_question => 'General Question',
    :job_offer_fulltime => 'Offer Full Time Position',
    :job_offer_consulting => 'Seeking Consultation',
    :job_offer_contract => 'Offer Contract-based Position',
    :provide_feedback => 'Provide Feedback'
  }

  EMAIL_REGEX = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i

  validates_presence_of   :name, :email, :phone, :preferred_method, :reason, :brief_msg
  validates_inclusion_of  :preferred_method, in: %w( email phone )
  validates_inclusion_of  :reason, in: %w( general_question job_offer_fulltime job_offer_consulting job_offer_contract provide_feedback )
  validates_length_of     :brief_msg, within: 1..255
  validates               :email, format: { with: EMAIL_REGEX, 
                                            message: 'is not valid' }
  validates               :phone, length: { minimum: 10, 
                                            maximum: 11,
                                            too_short: 'must have at least 10 digits',
                                            too_long: 'can\'t be more than 11 digits' },
                                  numericality: { only_integer: true }
  
  
end

app/models/image.rb
class Image < ApplicationRecord
  # constants
  IMAGE_URI_REGEX = /\A(?:([^:\/?#]+):)?(?:\/\/([^\/?#]*))?([^?#]*\.(?:jpg|gif|png|jpeg|svg))(?:\?([^#]*))?(?:#(.*))?\z/

  # validation rules
  validates  :source, presence: true,
                      format: { with: IMAGE_URI_REGEX }

  # relationships
  belongs_to :coverable, polymorphic: true, optional: true
end

app/models/project.rb
class Project < ApplicationRecord
  include Coverable

  # validation rules
  validates_presence_of   :name
  validates_presence_of   :date_completed
  validates_presence_of   :image, message: 'The cover of this project was not added.'
  validates               :link, presence: true, url: true

  # scopes
  def self.latest
    order(date_completed: :desc)
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  # validation rules
  validates_presence_of   :name

  # methods
  def name_in_dash_case
    name.gsub(/\s/, '-').downcase
  end

  def self.by_orderno
    order("orderno ASC")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/watched_video.rb
class WatchedVideo < ApplicationRecord
  include Coverable

  # validation rules
  validates_presence_of   :title
  validates_presence_of   :date_viewed
  validates               :link, presence: true,
                                 url: true
  validates_presence_of   :image, message: "Hey, the cover of this video you watched isn't going to add itself!"

  # scopes
  def self.last_viewed
    order(date_viewed: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include ExceptionHandler

  private
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to root_path, alert: "You are not authorized to view admin portal."
    end
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  # calls index view and displays a list of all books
  # that have been recorded as read
  def index
    @books = Book.all
  end
end

app/controllers/email_messages_controller.rb
class EmailMessagesController < ApplicationController
  # calls view to be rendered in order for user to create
  # a new email message
  def new
    @message = EmailMessage.new
  end

  # ingest valid parameters for sending a new email
  def create
    @message = EmailMessage.new(email_message_params)

    respond_to do |format|
      if @message.valid?
        EmailMessageMailer.with(message: @message).send_email.deliver_now
        format.html { redirect_to new_email_message_path, 
                      notice: 'Your message was successfully sent.'}
      else
        format.html { render :new }
      end
    end
  end

  private
  # specifies valid parameters that may be ingested when email message
  # is being submitted
  def email_message_params
    params.require(:email_message).permit(:name, 
                                          :company, 
                                          :email, 
                                          :phone, 
                                          :preferred_method, 
                                          :reason, 
                                          :brief_msg)
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    respond_to do |format|
      format.html { render status: 404 }
    end
  end

  def server_error
    respond_to do |format|
      format.html { render status: 500 }
    end    
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @projects = Project.latest
    @books = Book.last_read
    @watched_videos = WatchedVideo.last_viewed
    @skills = Skill.by_orderno
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # calls view to display list of projects
  def index
    @projects = Project.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :one_user_registered?, only: [:new, :create]
  
  protected
  def one_user_registered?
    if User.count == 1
      if user_signed_in?
        redirect_to root_path
      else
        redirect_to new_user_session_path
      end
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def display_form_errors_for instance
    html = ''
    error_messages = ''
    if instance.errors.any?
      html << "<div class='alert alert-danger' role='alert'>"
      html << "<h5 class='alert-heading'>There was an error. Fix the #{ pluralize(instance.errors.count, 'error') } below before attempting to save.</h5>"
      html << "<ul>"
      
      instance.errors.full_messages.each do |msg|
        error_messages << "<li>#{ msg }</li>"
      end
      
      html << error_messages
      html << "</ul></div>"

      html.html_safe
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/watched_videos_helper.rb
module WatchedVideosHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Admin | Full Stack Engineer | NYC | Kelvin Checo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
  </head>

  <body class="<%= current_page?(controller:'devise/sessions', action: 'new') ? 'text-center login-bg bg-light' : '' %>">

    <%= render 'shared/header' %>

    <!-- begin .container -->
    <div class="container pb-5">

      <% flash.each do |key, message| %>
        <div class="text-center alert
                    alert-<%= key == 'notice' ? 'light' : 'warning' %>" role="alert">
            <%= message %>
        </div>
      <% end %>

      <%= yield %>

    </div>
    <!--/ end .container -->

    <%= render 'shared/footer' unless current_page?(controller: 'devise/sessions', action: 'new') %>

    <!-- load js files -->
    <%= javascript_include_tag 'application' %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Full Stack Engineer | NYC | Kelvin Checo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">
  </head>

  <body class="<%= current_page?(controller:'devise/sessions', action: 'new') ? 'text-center login-bg bg-light' : '' %>">

    <%= render 'shared/header' %>

    <% flash.each do |key, message| %>
      <div class="text-center alert
                  alert-<%= key == 'notice' ? 'light' : 'warning' %>" role="alert">
          <%= message %>
      </div>
    <% end %>

    <%= yield %>

    <%= render 'shared/footer' unless current_page?(controller: 'devise/sessions', action: 'new') %>

    <!-- load js files -->
    <%= javascript_include_tag 'application' %>

  </body>
</html>

app/views/shared/_footer.html.erb
<% unless user_signed_in? %>

  <!-- begin .footer-nav -->
  <footer class="footer-nav navbar fixed-bottom navbar-expand navbar-dark bg-dark">
    <div class="container">
      <% unless current_page?(controller: 'email_messages', action: 'new') %>
        <%= link_to 'Work with me', new_email_message_path, class: 'nav-link contact-link text-light' %>
      <% else %>
        <%= link_to 'Home', root_path, class: 'nav-link contact-link text-light' %>
      <% end %>
      <ul class="navbar-nav flex-row ml-md-auto d-md-flex">
        <li class="nav-item">
          <a href="https://github.com/kcheco" class="nav-link p-md-2 p-3" target="_blank"><%= icon 'fab', "github" %></a>
        </li>
        <li class="nav-item">
          <a href="https://linkedin.com/in/kelvincheco25" class="nav-link p-md-2 p-3" target="_blank"><%= icon 'fab', 'linkedin' %></a>
        </li>        
        <li class="nav-item">
          <a href="https://instagram.com/kelvin.checo" class="nav-link p-md-2 p-3" target="_blank"><%= icon 'fab', 'instagram' %></a>
        </li>
        <li class="nav-item">
          <a href="mailto:checokelvin@gmail.com" class="nav-link p-md-2 p-3" target="_blank"><%= icon 'far', 'envelope' %></a>
        </li>
      </ul>
      <span class="navbar-text d-none ml-md-3">&copy; All rights reserved.</span>
    </div>
  </footer>
  <!--/ end .footer-nav -->

<% end %>

app/views/shared/_header.html.erb
<% if user_signed_in? %>

  <!-- begin header -->
  <header class="border-bottom">
    <nav class="navbar navbar-expand navbar-light bg-light">
      <a class="navbar-brand" href="#">Admin</a>
      <ul class="navbar-nav flex-row mx-md-auto ml-auto d-md-flex">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: 'nav-link px-md-3' %>
        </li>
        <li class="nav-item d-none d-md-block">
          <%= link_to "Books", admin_books_path, class: 'nav-link px-md-3' %>
        </li>
        <li class="nav-item d-none d-md-block">
          <%= link_to "WatchedVideos", admin_watched_videos_path, class: 'nav-link px-md-3' %>
        </li>
        <li class="nav-item d-none d-md-block">
          <%= link_to "Projects", admin_projects_path, class: 'nav-link px-md-3' %>
        </li>
        <li class="nav-item d-none d-md-block">
          <%= link_to "Skills", admin_skills_path, class: 'nav-link px-md-3' %>
        </li>
        <li class="nav-item dropdown d-block d-md-none">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Create
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "Books", admin_books_path, class: 'dropdown-item' %>
            <%= link_to "WatchedVideos", admin_watched_videos_path, class: 'dropdown-item' %>
            <%= link_to "Projects", admin_projects_path, class: 'dropdown-item' %>
            <%= link_to "Skills", admin_skills_path, class: 'dropdown-item' %>
          </div>
        </li>
      </ul>
      <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'btn btn-dark ml-3' %>
    </nav>
  </header>
  <!--/ end header -->

<% end %>