config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:sessions], controllers: { registrations: 'registrations' }
  as :user do
  #  get     'signup',       to: 'devise/registrations#new', as: 'new_user_registration_path'
  #  post    'signup',       to: 'devise/registrations#create', as: ''
   get     'admin/login',   to: 'devise/sessions#new',      as: 'new_user_session'
   post    'admin/login',   to: 'devise/sessions#create',   as: 'user_session'
   delete  'admin/logout',  to: 'devise/sessions#destroy',  as: 'destroy_user_session'
  end

  namespace 'admin' do
    resources :books, only: [ :new, :create, :edit, :update, :index, :destroy ]
    resources :watched_videos, only: [ :new, :create, :edit, :update, :index, :destroy ]
    resources :projects, only: [ :index, :new, :create, :edit, :update, :destroy ]
    resources :skills, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      put :sort, on: :collection
    end
  end

  resources :books, only: [ :index ]
  resources :watched_videos, only: [ :index ]
  resources :projects, only: [ :index ]

  get  '/contact_me',  to: 'email_messages#new',    as: 'new_email_message'
  post '/contact_me',  to: 'email_messages#create', as: 'email_message'

  match '/404',       to: 'errors#not_found',       via: :all
  match '/500',       to: 'errors#server_error',    via: :all
  match '*path',      to: 'errors#not_found',     via: :all

  root to: 'pages#home'
end

app/models/project.rb
class Project < ApplicationRecord
  include Coverable

  # validation rules
  validates_presence_of   :name
  validates_presence_of   :date_completed
  validates_presence_of   :image, message: 'The cover of this project was not added.'
  validates               :link, presence: true, url: true

  # scopes
  def self.latest
    order(date_completed: :desc)
  end
end

app/controllers/admin/projects_controller.rb
module Admin
  class ProjectsController < ApplicationController
    before_action :authenticate_user!, only: [ :index, :new, :edit, :destroy ]
    before_action :set_project, only: [ :edit, :update, :destroy ]
    layout "admin"

    # calls view to display list of projects
    def index
      @projects = Project.all
      render template: "projects/index"
    end

    # calls view that allows user to add a new projects to list
    # of completed projects
    def new
      @project = Project.new
    end

    # ingest valid parameters and adds a new project to list
    def create
      @project = Project.new(project_params)

      respond_to do |format|
        if @project.save
          format.html { redirect_to edit_admin_project_path(@project), 
                        notice: "Project was successfully added." }
        else
          format.html { render :new }
        end
      end
    end

    # calls view that allows user to apply view/changes to a specific
    # project
    def edit
    end

    # ingests valid parameters when apply changes to a specific project
    def update
      respond_to do |format|
        if @project.update(project_params)
          format.html { redirect_to edit_admin_project_path(@project), notice: "Project was successfully updated." }
        else
          format.html { render :edit }
        end
      end
    end

    # removes the specific project form request
    def destroy
      @project.destroy

      respond_to do |format|
        format.html { redirect_to admin_projects_path, notice: "Project was successfully deleted." }
      end
    end

    private
    # identifies a specific project based on id param in request
    def set_project
      @project = Project.find(params[:id])
    end

    # specifies valid parameters that may be ingested by the project resource
    def project_params
      params.require(:project).permit(:name,
                                      :date_completed,
                                      :link,
                                      image_attributes: [
                                        :id,
                                        :source,
                                        :_destroy
                                      ])
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  # calls view to display list of projects
  def index
    @projects = Project.all
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_project.html.erb
<% if project %>

  <div class="col-md-4 py-md-4 list-item project">
    <div class="rounded-corners overflow-hidden shadow-sm bg-light mb-md-3">
      <%= link_to image_tag(project.image.source, alt: "#{project.name}", title: "#{project.name}"), project.link, target: '_blank' %>
    </div>
    <div class="links">
      <div class="row px-3">
        <p class="text-muted mb-md-2"><%= project.name %></p>
      </div>
      <% if user_signed_in? %>
        <div class="row px-3 mb-5 mb-md-0">
          <%= link_to "Make Changes", edit_admin_project_path(project), class: 'btn btn-sm btn-outline-secondary mr-1' %>
          <%= link_to "Remove", admin_project_path(project), method: :delete, data: { confirm: 'Are you sure you no longer want to share this project?' }, class: 'btn btn-sm btn-outline-danger mx-md-1' %>
        </div>
      <% end %>
    </div>
  </div>

<% end %>

app/views/projects/edit.html.erb
<h1 class="mb-md-3">Editing a project</h1>

<%= form_for(@project) do |f| %>

  <%= display_form_errors_for @project %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :date_completed, "Date Completed" %>
    <%= f.text_field :date_completed, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control' %>
  </div>

  <% if @project.has_image? %>

    <div class="form-group">
      <%= f.fields_for :image do |image_form| %>
        <%= image_form.label :source, "Cover" %>
        <%= image_form.text_field :source, class: 'form-control' %>
      <% end %>
      <%= image_tag "#{@project.image.source}", class: 'mt-md-3' %>
    </div>

  <% end %>

  <div>
    <%= f.submit "Apply Changes", data: { disable_with: "Applying changes..."}, class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/projects/index.html.erb
<div class="container">
  <div class="w-100 my-3 py-3">

    <h3 class="my-3">List of Projects</h3>

    <% if user_signed_in? %>
    
      <%= link_to icon("fas", "plus-circle", "Add New Project"), new_admin_project_path, class: 'btn btn-dark mb-5' %>

    <% end %>

    <% @projects.in_groups_of(3).each do |projects_in_row| %>

      <div class="row">

        <%= render partial: 'projects/project', collection: projects_in_row, as: :project%>

      </div>

    <% end %>

  </div>
</div>

app/views/projects/new.html.erb
<h1 class="mb-md-3">Add a new project</h1>

<%= form_for(@project.with_no_cover) do |f| %>

  <%= display_form_errors_for @project %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: 'form-control', autofocus: 'true', placeholder: 'Enter the name of the project' %>
  </div>

  <div class="form-group">
    <%= f.label :date_completed, "Date Completed" %>
    <%= f.text_field :date_completed, class: 'form-control', placeholder: 'Enter date (yyyy-mm-dd)' %>
  </div>

  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control', placeholder: 'Enter the project\'s URL' %>
  </div>

  <%= f.fields_for :image do |image_form| %>
    <div class="form-group">
      <%= image_form.label :source, "Cover" %>
      <%= image_form.text_field :source, class: 'form-control', placeholder: 'Enter the image URL' %>
    </div>
  <% end %>

  <div>
    <%= f.submit "Add Project", data: { disable_with: "Adding Project..."}, class: 'btn btn-primary' %>
  </div>

<% end %>