config/routes.rb
Rails.application.routes.draw do

  devise_for :users, skip: [:sessions], controllers: { registrations: 'registrations' }
  as :user do
  #  get     'signup',       to: 'devise/registrations#new', as: 'new_user_registration_path'
  #  post    'signup',       to: 'devise/registrations#create', as: ''
   get     'admin/login',   to: 'devise/sessions#new',      as: 'new_user_session'
   post    'admin/login',   to: 'devise/sessions#create',   as: 'user_session'
   delete  'admin/logout',  to: 'devise/sessions#destroy',  as: 'destroy_user_session'
  end

  namespace 'admin' do
    resources :books, only: [ :new, :create, :edit, :update, :index, :destroy ]
    resources :watched_videos, only: [ :new, :create, :edit, :update, :index, :destroy ]
    resources :projects, only: [ :index, :new, :create, :edit, :update, :destroy ]
    resources :skills, only: [ :index, :new, :create, :edit, :update, :destroy ] do
      put :sort, on: :collection
    end
  end

  resources :books, only: [ :index ]
  resources :watched_videos, only: [ :index ]
  resources :projects, only: [ :index ]

  get  '/contact_me',  to: 'email_messages#new',    as: 'new_email_message'
  post '/contact_me',  to: 'email_messages#create', as: 'email_message'

  match '/404',       to: 'errors#not_found',       via: :all
  match '/500',       to: 'errors#server_error',    via: :all
  match '*path',      to: 'errors#not_found',     via: :all

  root to: 'pages#home'
end

app/models/watched_video.rb
class WatchedVideo < ApplicationRecord
  include Coverable

  # validation rules
  validates_presence_of   :title
  validates_presence_of   :date_viewed
  validates               :link, presence: true,
                                 url: true
  validates_presence_of   :image, message: "Hey, the cover of this video you watched isn't going to add itself!"

  # scopes
  def self.last_viewed
    order(date_viewed: :desc)
  end
end

app/controllers/admin/watched_videos_controller.rb
module Admin
  class WatchedVideosController < ApplicationController
    before_action :authenticate_user!, only: [ :index, :new, :edit, :destroy ]
    before_action :set_watched_video, only: [ :edit, :update, :destroy ]
    layout "admin"

    # calls index view and displays a list of all watched
    # videos that have been recorded
    def index
      @watched_videos = WatchedVideo.all
      render template: 'watched_videos/index'
    end

    # calls view to be rendered for user to add a youtube 
    # video they've watched
    def new
      @watched_video = WatchedVideo.new
    end

    # ingests valid parameters and adds a new watched video
    def create
      @watched_video = WatchedVideo.new(watched_video_params)

      respond_to do |format|
        if @watched_video.save
          format.html { redirect_to edit_admin_watched_video_path(@watched_video), 
                        notice: "Video was successfully added." }
        else
          format.html { render :new }
        end
      end
    end

    # calls view to be rendered for user to edit the details
    # of a watched video
    def edit
    end

    # ingests valid parametes and applies changes to exisiting watched
    # video
    def update
      respond_to do |format|
        if @watched_video.update(watched_video_params)
          format.html { redirect_to edit_admin_watched_video_path(@watched_video), 
                        notice: "Video was successfully updated." }
        else
          format.html { render :edit }
        end
      end
    end

    # removes a watched video from list
    def destroy
      @watched_video.destroy

      respond_to do |format|
        format.html { redirect_to admin_watched_videos_path, 
                      notice: "Video was successfully deleted."  }
      end
    end

    private
    # identifies a specific video from id parameter in request
    def set_watched_video
      @watched_video = WatchedVideo.find(params[:id])
    end

    # specifies valid parameters that may be ingested by the
    # watched video resource
    def watched_video_params
      params.require(:watched_video)
            .permit(:title,
                    :date_viewed,
                    :link,
                    image_attributes: [
                      :id,
                      :source,
                      :_destroy
                    ])
    end
  end
end

app/controllers/watched_videos_controller.rb
class WatchedVideosController < ApplicationController
  # calls index view and displays a list of all watched
  # videos that have been recorded
  def index
    @watched_videos = WatchedVideo.all
  end
end

app/helpers/watched_videos_helper.rb
module WatchedVideosHelper
end

app/views/watched_videos/_watched_video.html.erb
<% if video %>

  <div class="col-md-4 py-md-4 list-item watched_video">
    <div class="rounded-corners overflow-hidden shadow-sm bg-light mb-md-3">
      <%= link_to image_tag(video.image.source, alt: "#{video.title}", title: "#{video.title}"), video.link, target: '_blank' %>
    </div>
    <div class="links">
      <div class="row px-3">
        <p class="text-muted mb-md-2"><%= video.title %></p>
      </div>
      <% if user_signed_in? %>
      
        <div class="row px-3 mb-5 mb-md-0">
          <%= link_to "Make Changes", edit_admin_watched_video_path(video), class: 'btn btn-sm btn-outline-secondary mr-1' %>
          <%= link_to "Remove", admin_watched_video_path(video), method: :delete, data: { confirm: 'Are you sure you want to remove this video from your list?' }, class: 'btn btn-sm btn-outline-danger mx-md-1' %>
        </div>

      <% end %>
    </div>
  </div>

<% end %>

app/views/watched_videos/edit.html.erb
<h1 class="mb-md-3">Edit Watched Video</h2>

<%= form_for(@watched_video) do |f| %>

  <%= display_form_errors_for @watched_video %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :date_viewed, "Date Viewed" %>
    <%= f.text_field :date_viewed, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control' %>
  </div>

  <% if @watched_video.has_image? %>
    <div class="form-group">
      <%= f.fields_for :image do |image_form| %>
        <%= image_form.label :source, "Cover" %>
        <%= image_form.text_field :source, class: 'form-control' %>
      <% end %>
      <%= image_tag "#{@watched_video.image.source}", class: 'mt-md-3' %>
    </div>
  <% end %>

  <div>
    <%= f.submit "Apply Changes", data: { disable_with: "Applying changes..."}, class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/watched_videos/index.html.erb
<div class="container">
  <div class="w-100 my-3 py-3">

    <h3 class="my-3">List of Youtube Videos I've watched</h3>

    <% if user_signed_in? %>
    
      <%= link_to icon("fas", "plus-circle", "Add New Video"), new_admin_watched_video_path, class: 'btn btn-dark mb-5' %>

    <% end %>

    <% @watched_videos.in_groups_of(3).each do |videos_for_row| %>

      <div class="row">

        <%= render partial: 'watched_videos/watched_video', collection: videos_for_row, as: :video %>

      </div>

    <% end %>

  </div>
</div>

app/views/watched_videos/new.html.erb
<h1 class="mb-md-3">Add a video you watched</h1>

<%= form_for(@watched_video.with_no_cover) do |f| %>

  <%= display_form_errors_for @watched_video %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control', autofocus: 'true', placeholder: 'Enter the title' %>
  </div>

  <div class="form-group">
    <%= f.label :date_viewed, "Date Viewed" %>
    <%= f.text_field :date_viewed, class: 'form-control', placeholder: 'Enter date (yyyy-mm-dd)' %>
  </div>

  <div class="form-group">
    <%= f.label :link %>
    <%= f.text_field :link, class: 'form-control', placeholder: 'Enter the youtube video URL' %>
  </div>

  <%= f.fields_for :image do |image_form| %>
    <div class="form-group">
      <%= image_form.label :source, "Cover" %>
      <%= image_form.text_field :source, class: 'form-control', placeholder: 'Enter the image URL' %>
    </div>
  <% end %>

  <div>
    <%= f.submit "Add Video", data: { disable_with: "Adding Video..."}, class: 'btn btn-primary' %>
  </div>

<% end %>